haagahelia/Siba_be

src/routes/department.ts
src/validationHandler/index.ts

Department crudl part 2

---

src/routes/department.ts

Change the endpoints in update and get all functionalities to fit minimalistic url

Update Department endpoints

---

src/index.ts
src/types.ts

Backend index suraj

---

src/authorization/admin.ts
src/authorization/planner.ts
src/authorization/roleChecker.ts
src/authorization/statist.ts
src/authorization/userValidation.ts

import of external and internal modules seperated by space and added comment after dotenv.config()

import of external and internal modules seperated

---

src/routes/building.ts

extracted error handling to reduce redundancy and refactored

extracted error handling 

---

src/routes/department.ts

Validate added and roles are changed according to the CRUD Excel file

author roles fixed 

---

src/routes/user.ts

Added a new route in user.ts for building the frontend userlist functionality.

Added a new route for user.ts for fetching user information

---

src/routes/user.ts
src/validationHandler/user.ts

Also added a basic validation to use when updating user data.

Added delete and update routes for user in user.ts

---

src/authorization/admin.ts
src/authorization/oneRoleRequirementHandler.ts
src/authorization/planner.ts
src/authorization/roleChecker.ts
src/authorization/statist.ts
src/authorization/userValidation.ts
src/responseHandler/index.ts
src/routes/allocRound.ts
src/routes/allocation.ts
src/routes/building.ts
src/routes/department.ts
src/services/allocation.ts
src/services/program.ts
src/types/custom.ts
src/types/express/index.d.ts
src/validationHandler/index.ts
tsconfig.json

- 21908dbe00476c44b7e4d62910a78d258d0b2b60 Use `const` instead of `let` when not reassigned
- 307ab250b67438beae28bdd56c062b6cfd9fee64 Avoid reassigning a function parameter
- d4d6e460d56ec8eb0ea2a826cee1b5f8566dc003 Avoid the `any` type and improve typings

Fix all linting errors

---

package.json
src/db/index_knex.ts

Removes the workaround introduced in #180.

Upgrade Knex

---

request/Spaces.rest

Created rest test file for spaces. Get space by ID is not included as it technically does not exist.

Adds rest test for spaces

---

Database/Documentation/allocation_versioning.md

First version of the Versioning plan for comments

---

src/routes/resetDatabase.ts

- Lets also keep the commented codes there if somebody in future likes to change it.

sql statements executed with knex

---

request/DepartmentPlanner.rest
src/routes/departmentplanner.ts

Added rest test for department planner routes. Filled in missing crud routes to the departmentplanner.ts for better rest tests and in case of future use.

Departmentplanner rest test and missing routes jesse

---

src/routes/program.ts

Changed for faster frontend calculations and handling.

Changed route to return program id instead of name

---

Database/Documentation/database_descriptions.md

Updated the backend documentation with the current SQL Scripts so that all new added attributes are defined and listed.

updated backend documentation

---

README.md
src/services/allocation.ts

Minor wording changes in the README.md and the comment line in the allocation.ts

improve wording in README.md and allocation.ts

---

src/validationHandler/building.ts
src/validationHandler/subject.ts

Spelling mistakes for comments are changed in subject.ts and building.ts files

Git assignment aleksei

---

README.md

few changes made in Readme file

readme-changed

---

README.md

remove extra spaces and improve text

---

README.md

Git assignment 2 vivienne

---

src/routes/subjectEquipment.ts
src/validationHandler/subjectEquipment.ts

Changed the SubjectEquipment to use knex in update and delete. Requires a few changes in FE to display deletion/edit correctly.

Subject equipment delete and update to knex olli

---

request/SubjectEquipment.rest

Made some rest tests for the SubjectEquipment for Adding a new equipment, deleting an equipment, updating an existing equipment and getting the subjects and getting equipment.

Tests for subject equipment olli

---

request/Program.rest
src/routes/program.ts

A new route added in src/routes/program.ts for fetching number of lessons for a selected program

Number of lessons get route add jonas

---

src/routes/program.ts

Added the validator to  the route  - src/routes/program.ts

ProgramId validator

---

request/SubjectEquipment.rest
src/routes/equipment.ts
src/routes/subjectEquipment.ts

authorized planner to add, delete and update the subject equipment's

Planner auth changes zafar

---

request/SpaceType.rest
src/routes/spaceType.ts

All for SpaceType. Added routing for GetById. Edited routing for GetAall. Added .rest file for testing and requests for both GetById and GetAll.

SpaceType routing.

---

request/Department.rest
request/DepartmentPlanner.rest
src/routes/department.ts

Fixed department put validation not working by adding missing validate middleware. Also updated Department.rest file.

Department put validation fixed and Department rest tests updated

---

biome.json
request/Spaces.rest
src/routes/space.ts

My commit comment is meant to be " modified space.ts and space.rest file"

Delete render building spaces be fred

---

package.json
src/routes/building.ts

Added get numberOfSpaces in single building method in building route folder.

Conditional rendering DNA(on delete no action) for building

---

src/routes/allocation.ts

Created db_knex to get full report of the allocation and the report for planner. Right now, they get Department, Program, Lesson and Room from the database to the frontend and planner report also checks the user id to get only their departments lessons.

Excel import changes olli

---

src/routes/allocation.ts
src/services/allocation.ts
src/services/program.ts
src/types/custom.ts

Changed all the code in services>allocation.ts and program.ts to use db_knex. Everything seems to be working fine.
Also changed the time_to_sec to use the extract method to get the times to avoid overflow.
And added ordering to planner report while at it.

Services to knex olli

---

src/routes/department.ts

The logic is updated a bit for providing names of programs of selected department to front end.

src: router: fetch program list of a selected department by id

---

src/routes/department.ts

-get number of programs
-get all program names
-get top 5 program names (first five from the result set)

src: router: department.ts : created 3 end points to,

---

src/routes/spaceType.ts
src/services/allocation.ts

SpaceType POST request and program results gave 500 internal server error because there were 2 typos in database table names. I fixed them.

Fixed SpaceType and AllocSpace database table typos

---

src/services/allocation.ts

There were other parts that used the EXTRACT(HOUR from ....) in the code that caused the same issue  Juuso fixed on Wednesday. Changed those to use HOUR(...) instead. Still some issue with how the subject gets allocated to a room that does not have enough hours.

Changed all the hour extractions to use HOUR instead of EXTRACT

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
src/routes/space.ts

databse: updated space table DNA for the allocSpace and allocSuitableSpace previously was CASCADE. 
space.ts: created backend service to fetching total no. of allocations associated with space by space id

Fetch alloc for space by id zafar

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
src/routes/equipment.ts

router: equipment: created 2 services to fetch count and names of subject associated to equipment by id.

Equipment conditional rendering for delete button zafar

---

src/routes/equipment.ts

equipment.ts: changed subjectId to subjectCount.

router: equipment.ts: changed subjectId to subjectCount.

---

src/routes/space.ts

router:space.ts:
- fetching first five names of allocrounds associated to a space by id

router:space.ts: fetching first five names of allocrounds

---

src/routes/allocation.ts

Added Last Successful and Last Failed Calculation to the report knex. Only makes sense if the FE branch with same name is accepted.

Success and fail to report olli

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/02__insert_test_data.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
request/SpaceType.rest
src/routes/spaceType.ts
src/validationHandler/index.ts
src/validationHandler/spaceType.ts

Now there are acronyms added for each SpaceType

Space Type Acronyms

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/01_create_procedures.sql
Database/SQL_Scripts/02__insert_test_data.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
src/routes/allocation.ts
src/services/allocation.ts

Changed totalTime to BIGINT
Changed testData to be BIGINT seconds
Changed procedures to calculate totalTime as seconds and adding sessionLength times as seconds
Changed db_knex to work totalTime as seconds (totalTime/60/60 as hours)

Procedure changes olli

---

src/services/allocation.ts

Fixed the sorting view for the room results, previously it was based on the total hours now its based on the percentage.

fixed the sorting view (room results)

---

package.json
src/routes/space.ts

Space conditional rendering fix. Shows allocation simulations accosiated with space

Space condRendering allocSimulation count

---

src/services/allocation.ts

fixed the sorting , first by allocation and then by name.

fixed the sorting.

---

src/routes/allocation.ts
src/services/allocation.ts

Moved report db_knex to services so that allocation.ts routes will all be in the same format.
Changed the aliases in all of the db_knex code to follow the same naming convention for readability.

Allocation refactoring olli

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
request/AllocRound.rest
src/routes/allocRound.ts
src/validationHandler/allocRound.ts

Made a slight mistake in allocRound.ts line 31, I mistakenly deleted/removed statist

backend implementation for read-only

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
request/Spaces.rest
src/routes/space.ts
src/types/custom.ts
src/validationHandler/index.ts
src/validationHandler/space.ts

- Added a new column 'isLowNoise' to the 'Space' database table
- Updated the space backend routes to use isLowNoise field in request body
- Changed posting spaces to use validation as it was missing it for some reason
- Updated Spaces.rest tests
- Fixed some time validation mistakes

Spaces can be marked as "low noise"

---

src/services/allocation.ts

To get them to the AllocationSubjectFailureView

Added isNoisy to getUnAllocableSubjects and islowNoise to getSpacesForSubject

---

Database/SQL_Scripts/000__CreateALLdb.sql
Database/SQL_Scripts/01__create_tables.sql
Database/SQL_Scripts/06__drop_tables_create_tables_insert_test_data.sql
request/Subject.rest
src/validationHandler/subject.ts

Update spaceTypeId column to be NOT NULL in Subject table

---

src/routes/allocRound.ts

- Remove hardcoded userID (201) in POST /allocRound
- Use userID from request body instead

Refactor allocRound route to use userId from request body
